<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 8 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record ((MetadataEntry|HeartRateVariabilityMetadataList)*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent|WorkoutRoute)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type         CDATA #REQUIRED
  date         CDATA #REQUIRED
  duration     CDATA #IMPLIED
  durationUnit CDATA #IMPLIED
>
<!ELEMENT WorkoutRoute ((MetadataEntry|Location)*)>
<!ATTLIST WorkoutRoute
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Location EMPTY>
<!ATTLIST Location
  date               CDATA #REQUIRED
  latitude           CDATA #REQUIRED
  longitude          CDATA #REQUIRED
  altitude           CDATA #REQUIRED
  horizontalAccuracy CDATA #REQUIRED
  verticalAccuracy   CDATA #REQUIRED
  course             CDATA #REQUIRED
  speed              CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. -->
<!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute*)>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute
  bpm  CDATA #REQUIRED
  time CDATA #REQUIRED
>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord
  type              CDATA #REQUIRED
  identifier        CDATA #REQUIRED
  sourceName        CDATA #REQUIRED
  sourceURL         CDATA #REQUIRED
  fhirVersion       CDATA #REQUIRED
  receivedDate      CDATA #REQUIRED
  resourceFilePath  CDATA #REQUIRED
>
]>
<HealthData locale="ja_JP">
 <ExportDate value="2019-04-08 19:23:23 +0900"/>
 <Me HKCharacteristicTypeIdentifierDateOfBirth="2000-01-26" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexMale" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="ヘルスケア" sourceVersion="11.2.5" unit="cm" creationDate="2018-02-20 07:56:45 +0900" startDate="2018-02-20 07:56:45 +0900" endDate="2018-02-20 07:56:45 +0900" value="168"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="HealthData Importer" sourceVersion="1" unit="cm" creationDate="2018-02-21 00:55:43 +0900" startDate="2017-08-04 22:36:00 +0900" endDate="2017-08-04 22:36:00 +0900" value="167"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="ヘルスケア" sourceVersion="12.2" unit="cm" creationDate="2019-04-08 19:22:16 +0900" startDate="2019-04-05 12:00:00 +0900" endDate="2019-04-05 12:00:00 +0900" value="168.5">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="HealthData Importer" sourceVersion="1" unit="kg" creationDate="2018-02-21 00:55:43 +0900" startDate="2017-08-04 22:36:00 +0900" endDate="2017-08-04 22:36:00 +0900" value="55"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="ヘルスケア" sourceVersion="11.2.5" unit="kg" creationDate="2018-02-20 07:56:45 +0900" startDate="2018-02-20 07:56:45 +0900" endDate="2018-02-20 07:56:45 +0900" value="52"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="ヘルスケア" sourceVersion="12.2" unit="kg" creationDate="2019-04-08 19:22:56 +0900" startDate="2019-04-05 12:00:00 +0900" endDate="2019-04-05 12:00:00 +0900" value="51">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="myApple Watch 44" sourceVersion="5.2" device="&lt;&lt;HKDevice: 0x2822649b0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch4,2, software:5.2&gt;" unit="count/min" creationDate="2019-04-08 19:18:25 +0900" startDate="2019-04-08 19:15:59 +0900" endDate="2019-04-08 19:15:59 +0900" value="59">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierStepCount" sourceName="myiPhone" sourceVersion="12.2" device="&lt;&lt;HKDevice: 0x2821d5590&gt;, name:iPhone, manufacturer:Apple, model:iPhone, hardware:iPhone11,8, software:12.2&gt;" unit="count" creationDate="2019-04-08 19:22:26 +0900" startDate="2019-04-08 19:07:23 +0900" endDate="2019-04-08 19:07:31 +0900" value="18"/>
 <Record type="HKQuantityTypeIdentifierDistanceWalkingRunning" sourceName="myiPhone" sourceVersion="12.2" device="&lt;&lt;HKDevice: 0x2821bd9f0&gt;, name:iPhone, manufacturer:Apple, model:iPhone, hardware:iPhone11,8, software:12.2&gt;" unit="km" creationDate="2019-04-08 19:22:26 +0900" startDate="2019-04-08 19:07:23 +0900" endDate="2019-04-08 19:07:31 +0900" value="0.0121081"/>
 <Record type="HKQuantityTypeIdentifierBasalEnergyBurned" sourceName="myApple Watch 44" sourceVersion="5.2" device="&lt;&lt;HKDevice: 0x282183890&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch4,2, software:5.2&gt;" unit="kcal" creationDate="2019-04-08 19:08:48 +0900" startDate="2019-04-08 19:08:05 +0900" endDate="2019-04-08 19:08:36 +0900" value="0.576"/>
 <Record type="HKQuantityTypeIdentifierActiveEnergyBurned" sourceName="myApple Watch 44" sourceVersion="5.2" device="&lt;&lt;HKDevice: 0x28221ff20&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch4,2, software:5.2&gt;" unit="kcal" creationDate="2019-04-08 19:21:29 +0900" startDate="2019-04-08 19:17:30 +0900" endDate="2019-04-08 19:18:21 +0900" value="0.211"/>
 <Record type="HKQuantityTypeIdentifierFlightsClimbed" sourceName="myiPhone" sourceVersion="12.2" device="&lt;&lt;HKDevice: 0x2821c7b10&gt;, name:iPhone, manufacturer:Apple, model:iPhone, hardware:iPhone11,8, software:12.2&gt;" unit="count" creationDate="2019-04-08 18:44:16 +0900" startDate="2019-04-08 18:33:57 +0900" endDate="2019-04-08 18:34:00 +0900" value="1"/>
 <Record type="HKQuantityTypeIdentifierNumberOfTimesFallen" sourceName="myApple Watch 44" unit="count" creationDate="2018-10-03 16:18:52 +0900" startDate="2018-10-03 16:18:08 +0900" endDate="2018-10-03 16:18:08 +0900" value="1">
  <MetadataEntry key="HKFallActionRequested" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierNumberOfTimesFallen" sourceName="myApple Watch 44" unit="count" creationDate="2019-01-24 09:33:57 +0900" startDate="2019-01-24 09:33:14 +0900" endDate="2019-01-24 09:33:14 +0900" value="1">
  <MetadataEntry key="HKFallActionRequested" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierAppleExerciseTime" sourceName="myApple Watch 44" sourceVersion="5.2" device="&lt;&lt;HKDevice: 0x282208b40&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch4,2, software:5.2&gt;" unit="min" creationDate="2019-04-08 18:37:10 +0900" startDate="2019-04-08 18:33:44 +0900" endDate="2019-04-08 18:34:44 +0900" value="1"/>
 <Record type="HKQuantityTypeIdentifierDistanceCycling" sourceName="myApple Watch 44" sourceVersion="5.1.2" device="&lt;&lt;HKDevice: 0x282215e50&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch4,2, software:5.1.2&gt;" unit="km" creationDate="2018-12-15 15:10:35 +0900" startDate="2018-12-15 15:10:30 +0900" endDate="2018-12-15 15:10:35 +0900" value="3.21564e-05"/>
 <Record type="HKQuantityTypeIdentifierRestingHeartRate" sourceName="myApple Watch 44" sourceVersion="5.2" unit="count/min" creationDate="2019-04-08 07:37:10 +0900" startDate="2019-04-08 00:56:30 +0900" endDate="2019-04-08 07:35:20 +0900" value="41"/>
 <Record type="HKQuantityTypeIdentifierVO2Max" sourceName="myApple Watch 44" unit="mL/min·kg" creationDate="2019-04-03 20:16:04 +0900" startDate="2019-04-03 20:16:03 +0900" endDate="2019-04-03 20:16:03 +0900" value="45.667">
  <MetadataEntry key="HKVO2MaxTestType" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingHeartRateAverage" sourceName="myApple Watch 44" sourceVersion="5.2" unit="count/min" creationDate="2019-04-08 08:22:31 +0900" startDate="2019-04-08 00:56:30 +0900" endDate="2019-04-08 08:21:57 +0900" value="125"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="時計" sourceVersion="50" device="&lt;&lt;HKDevice: 0x282186c60&gt;, name:iPhone, manufacturer:Apple, model:iPhone, hardware:iPhone10,1, software:11.2.6&gt;" creationDate="2018-03-09 07:00:11 +0900" startDate="2018-03-09 02:29:36 +0900" endDate="2018-03-09 07:00:06 +0900" value="HKCategoryValueSleepAnalysisInBed">
  <MetadataEntry key="HKTimeZone" value="Asia/Tokyo"/>
 </Record>
 <Record type="HKCategoryTypeIdentifierAppleStandHour" sourceName="myApple Watch 44" sourceVersion="5.2" device="&lt;&lt;HKDevice: 0x2822bb660&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch4,2, software:5.2&gt;" creationDate="2019-04-08 19:08:13 +0900" startDate="2019-04-08 19:00:00 +0900" endDate="2019-04-08 20:00:00 +0900" value="HKCategoryValueAppleStandHourStood"/>
 <Record type="HKCategoryTypeIdentifierMindfulSession" sourceName="myApple Watch 44" sourceVersion="5.1.3" creationDate="2019-01-31 13:54:33 +0900" startDate="2019-01-31 13:53:30 +0900" endDate="2019-01-31 13:54:30 +0900"/>
 <Record type="HKCategoryTypeIdentifierLowHeartRateEvent" sourceName="myApple Watch 44" sourceVersion="5.2" device="&lt;&lt;HKDevice: 0x2822b4b40&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch4,2, software:5.2&gt;" creationDate="2019-04-04 06:29:43 +0900" startDate="2019-04-04 06:19:20 +0900" endDate="2019-04-04 06:29:20 +0900">
  <MetadataEntry key="HKHeartRateEventThreshold" value="40 count/min"/>
 </Record>
 <Workout workoutActivityType="HKWorkoutActivityTypeWalking" duration="36.06794809103012" durationUnit="min" totalDistance="2.543598162392106" totalDistanceUnit="km" totalEnergyBurned="87.23091460338068" totalEnergyBurnedUnit="kcal" sourceName="myApple Watch 44" sourceVersion="5.2" device="&lt;&lt;HKDevice: 0x2822bfe80&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch4,2, software:5.2&gt;" creationDate="2019-04-03 20:16:05 +0900" startDate="2019-04-03 19:39:59 +0900" endDate="2019-04-03 20:16:03 +0900">
  <MetadataEntry key="HKTimeZone" value="Asia/Tokyo"/>
  <MetadataEntry key="HKIndoorWorkout" value="0"/>
  <MetadataEntry key="HKWeatherTemperature" value="46 degF"/>
  <MetadataEntry key="HKWeatherHumidity" value="52 %"/>
  <WorkoutEvent type="HKWorkoutEventTypeSegment" date="2019-04-03 19:39:59 +0900" duration="11.53675056497256" durationUnit="min"/>
  <WorkoutEvent type="HKWorkoutEventTypeSegment" date="2019-04-03 19:39:59 +0900" duration="19.02301025390625" durationUnit="min"/>
  <WorkoutEvent type="HKWorkoutEventTypeSegment" date="2019-04-03 19:51:31 +0900" duration="12.83394253452619" durationUnit="min"/>
  <WorkoutEvent type="HKWorkoutEventTypeSegment" date="2019-04-03 19:59:01 +0900" duration="16.85766378045082" durationUnit="min"/>
  <WorkoutEvent type="HKWorkoutEventTypeSegment" date="2019-04-03 20:04:21 +0900" duration="11.50998093485832" durationUnit="min"/>
  <WorkoutRoute sourceName="myApple Watch 44" sourceVersion="12.2" creationDate="2019-04-03 20:35:28 +0900" startDate="2019-04-03 19:50:07 +0900" endDate="2019-04-03 20:11:14 +0900">
   <MetadataEntry key="HKMetadataKeySyncVersion" value="2"/>
   <MetadataEntry key="HKMetadataKeySyncIdentifier" value="D636400A-5FAB-4F03-B8F0-43D1EA05E3B4"/>
   <Location date="2019-04-03 19:50:07 +0900" latitude="35.0194" longitude="135.772" altitude="49.5523" horizontalAccuracy="5.04842" verticalAccuracy="3.5701" course="187.898" speed="0.638442"/>
   <Location date="2019-04-03 19:50:08 +0900" latitude="35.0194" longitude="135.772" altitude="49.5333" horizontalAccuracy="4.67152" verticalAccuracy="3.30359" course="172.198" speed="0.639353"/>
   <Location date="2019-04-03 19:50:09 +0900" latitude="35.0194" longitude="135.772" altitude="49.5142" horizontalAccuracy="4.32027" verticalAccuracy="3.05523" course="188.39" speed="0.642333"/>
   <Location date="2019-04-03 19:50:10 +0900" latitude="35.0194" longitude="135.772" altitude="49.4949" horizontalAccuracy="3.99265" verticalAccuracy="2.82358" course="205.918" speed="0.648007"/>
   <Location date="2019-04-03 19:50:11 +0900" latitude="35.0193" longitude="135.772" altitude="49.4754" horizontalAccuracy="3.69252" verticalAccuracy="2.61135" course="187.359" speed="0.656727"/>
   <Location date="2019-04-03 19:50:12 +0900" latitude="35.0193" longitude="135.772" altitude="49.4555" horizontalAccuracy="3.41941" verticalAccuracy="2.41825" course="203.726" speed="0.668743"/>
   <Location date="2019-04-03 19:50:13 +0900" latitude="35.0193" longitude="135.772" altitude="49.4354" horizontalAccuracy="3.17356" verticalAccuracy="2.24441" course="201.447" speed="0.684106"/>
   <Location date="2019-04-03 19:50:14 +0900" latitude="35.0193" longitude="135.772" altitude="49.4158" horizontalAccuracy="2.96528" verticalAccuracy="2.09714" course="194.609" speed="0.700789"/>
   <Location date="2019-04-03 19:50:15 +0900" latitude="35.0193" longitude="135.772" altitude="49.3991" horizontalAccuracy="2.8092" verticalAccuracy="1.98677" course="198.475" speed="0.714278"/>
   <Location date="2019-04-03 19:50:16 +0900" latitude="35.0193" longitude="135.772" altitude="49.3791" horizontalAccuracy="2.64724" verticalAccuracy="1.87225" course="201.693" speed="0.735195"/>
   <Location date="2019-04-03 19:50:17 +0900" latitude="35.0193" longitude="135.772" altitude="49.3587" horizontalAccuracy="2.50897" verticalAccuracy="1.77449" course="197.465" speed="0.757885"/>
   <Location date="2019-04-03 19:50:18 +0900" latitude="35.0193" longitude="135.772" altitude="49.3382" horizontalAccuracy="2.39297" verticalAccuracy="1.69246" course="187.959" speed="0.782054"/>
   <Location date="2019-04-03 19:50:19 +0900" latitude="35.0193" longitude="135.772" altitude="49.3174" horizontalAccuracy="2.29742" verticalAccuracy="1.6249" course="186.559" speed="0.807485"/>
   <Location date="2019-04-03 19:50:20 +0900" latitude="35.0193" longitude="135.772" altitude="49.2965" horizontalAccuracy="2.2202" verticalAccuracy="1.57029" course="195.178" speed="0.834048"/>
   <Location date="2019-04-03 19:50:21 +0900" latitude="35.0193" longitude="135.772" altitude="49.2754" horizontalAccuracy="2.15899" verticalAccuracy="1.52701" course="179.446" speed="0.861647"/>
   <Location date="2019-04-03 19:50:22 +0900" latitude="35.0193" longitude="135.772" altitude="49.2542" horizontalAccuracy="2.11143" verticalAccuracy="1.49338" course="178.771" speed="0.890129"/>
   <Location date="2019-04-03 19:50:23 +0900" latitude="35.0193" longitude="135.772" altitude="49.2328" horizontalAccuracy="2.07523" verticalAccuracy="1.46777" course="174.629" speed="0.919288"/>
   <Location date="2019-04-03 19:50:23 +0900" latitude="35.0193" longitude="135.772" altitude="49.2112" horizontalAccuracy="2.04826" verticalAccuracy="1.4487" course="169.099" speed="0.948937"/>
   <Location date="2019-04-03 19:50:24 +0900" latitude="35.0193" longitude="135.772" altitude="49.1883" horizontalAccuracy="2.02705" verticalAccuracy="1.4337" course="167.703" speed="0.982164"/>
   <Location date="2019-04-03 19:50:25 +0900" latitude="35.0192" longitude="135.772" altitude="49.1651" horizontalAccuracy="2.01056" verticalAccuracy="1.42203" course="153.629" speed="1.01555"/>
   <Location date="2019-04-03 19:50:26 +0900" latitude="35.0192" longitude="135.772" altitude="49.1415" horizontalAccuracy="1.99714" verticalAccuracy="1.41254" course="165.289" speed="1.04876"/>
   <Location date="2019-04-03 19:50:27 +0900" latitude="35.0192" longitude="135.772" altitude="49.1176" horizontalAccuracy="1.98553" verticalAccuracy="1.40434" course="183.437" speed="1.08141"/>
   <Location date="2019-04-03 19:50:28 +0900" latitude="35.0192" longitude="135.772" altitude="49.0933" horizontalAccuracy="1.97482" verticalAccuracy="1.39676" course="167.291" speed="1.1131"/>
   <Location date="2019-04-03 19:50:29 +0900" latitude="35.0192" longitude="135.772" altitude="49.0685" horizontalAccuracy="1.96441" verticalAccuracy="1.3894" course="179.633" speed="1.14347"/>
   <Location date="2019-04-03 19:50:30 +0900" latitude="35.0192" longitude="135.772" altitude="49.0433" horizontalAccuracy="1.95395" verticalAccuracy="1.382" course="174.504" speed="1.17218"/>
   <Location date="2019-04-03 19:50:31 +0900" latitude="35.0192" longitude="135.772" altitude="49.0177" horizontalAccuracy="1.94331" verticalAccuracy="1.37448" course="169.821" speed="1.19893"/>
   <Location date="2019-04-03 19:50:32 +0900" latitude="35.0192" longitude="135.772" altitude="48.9916" horizontalAccuracy="1.93252" verticalAccuracy="1.36685" course="172.274" speed="1.22345"/>
   <Location date="2019-04-03 19:50:33 +0900" latitude="35.0192" longitude="135.772" altitude="48.9651" horizontalAccuracy="1.92168" verticalAccuracy="1.35918" course="182.826" speed="1.24551"/>
   <Location date="2019-04-03 19:50:34 +0900" latitude="35.0192" longitude="135.772" altitude="48.938" horizontalAccuracy="1.91094" verticalAccuracy="1.35159" course="176.324" speed="1.26493"/>
   <Location date="2019-04-03 19:50:35 +0900" latitude="35.0191" longitude="135.772" altitude="48.9104" horizontalAccuracy="1.90046" verticalAccuracy="1.34418" course="174.248" speed="1.28172"/>
   <Location date="2019-04-03 19:50:36 +0900" latitude="35.0191" longitude="135.772" altitude="48.8822" horizontalAccuracy="1.89039" verticalAccuracy="1.33705" course="171.758" speed="1.29598"/>
   <Location date="2019-04-03 19:50:37 +0900" latitude="35.0191" longitude="135.772" altitude="48.8535" horizontalAccuracy="1.88083" verticalAccuracy="1.3303" course="170.774" speed="1.30807"/>
   <Location date="2019-04-03 19:50:38 +0900" latitude="35.0191" longitude="135.772" altitude="48.8242" horizontalAccuracy="1.87185" verticalAccuracy="1.32394" course="161.366" speed="1.31839"/>
   <Location date="2019-04-03 19:50:39 +0900" latitude="35.0191" longitude="135.772" altitude="48.7943" horizontalAccuracy="1.86346" verticalAccuracy="1.31801" course="170.494" speed="1.32731"/>
   <Location date="2019-04-03 19:50:40 +0900" latitude="35.0191" longitude="135.772" altitude="48.7639" horizontalAccuracy="1.8557" verticalAccuracy="1.31252" course="173.202" speed="1.33513"/>
   <Location date="2019-04-03 19:50:41 +0900" latitude="35.0191" longitude="135.772" altitude="48.7329" horizontalAccuracy="1.84857" verticalAccuracy="1.30748" course="168.227" speed="1.34214"/>
   <Location date="2019-04-03 19:50:42 +0900" latitude="35.0191" longitude="135.772" altitude="48.7015" horizontalAccuracy="1.84212" verticalAccuracy="1.30292" course="174.252" speed="1.34861"/>
   <Location date="2019-04-03 19:50:43 +0900" latitude="35.019" longitude="135.772" altitude="48.6697" horizontalAccuracy="1.8363" verticalAccuracy="1.2988" course="176.16" speed="1.35478"/>
   <Location date="2019-04-03 19:50:44 +0900" latitude="35.019" longitude="135.772" altitude="48.6374" horizontalAccuracy="1.83106" verticalAccuracy="1.2951" course="174.819" speed="1.36085"/>
   <Location date="2019-04-03 19:50:45 +0900" latitude="35.019" longitude="135.772" altitude="48.6048" horizontalAccuracy="1.82632" verticalAccuracy="1.29174" course="169.455" speed="1.36698"/>
   <Location date="2019-04-03 19:50:46 +0900" latitude="35.019" longitude="135.772" altitude="48.572" horizontalAccuracy="1.82202" verticalAccuracy="1.2887" course="167.242" speed="1.3733"/>
   <Location date="2019-04-03 19:50:47 +0900" latitude="35.019" longitude="135.772" altitude="48.5389" horizontalAccuracy="1.81813" verticalAccuracy="1.28595" course="171.842" speed="1.37993"/>
   <Location date="2019-04-03 19:50:48 +0900" latitude="35.019" longitude="135.772" altitude="48.5055" horizontalAccuracy="1.81462" verticalAccuracy="1.28347" course="175.96" speed="1.38705"/>
   <Location date="2019-04-03 19:50:49 +0900" latitude="35.019" longitude="135.772" altitude="48.4721" horizontalAccuracy="1.81143" verticalAccuracy="1.28121" course="182.009" speed="1.39477"/>
   <Location date="2019-04-03 19:50:50 +0900" latitude="35.019" longitude="135.772" altitude="48.4386" horizontalAccuracy="1.80849" verticalAccuracy="1.27913" course="182.736" speed="1.40318"/>
   <Location date="2019-04-03 19:50:51 +0900" latitude="35.0189" longitude="135.772" altitude="48.405" horizontalAccuracy="1.80573" verticalAccuracy="1.27718" course="182.901" speed="1.41224"/>
   <Location date="2019-04-03 19:50:52 +0900" latitude="35.0189" longitude="135.772" altitude="48.3716" horizontalAccuracy="1.80306" verticalAccuracy="1.27529" course="182.405" speed="1.42183"/>
   <Location date="2019-04-03 19:50:53 +0900" latitude="35.0189" longitude="135.772" altitude="48.3384" horizontalAccuracy="1.80043" verticalAccuracy="1.27343" course="182.666" speed="1.43172"/>
   <Location date="2019-04-03 19:50:54 +0900" latitude="35.0189" longitude="135.772" altitude="48.3055" horizontalAccuracy="1.79781" verticalAccuracy="1.27158" course="186.73" speed="1.44153"/>
   <Location date="2019-04-03 19:50:55 +0900" latitude="35.0189" longitude="135.772" altitude="48.273" horizontalAccuracy="1.79518" verticalAccuracy="1.26971" course="185.601" speed="1.45089"/>
   <Location date="2019-04-03 19:50:56 +0900" latitude="35.0189" longitude="135.772" altitude="48.2409" horizontalAccuracy="1.79255" verticalAccuracy="1.26786" course="184.985" speed="1.45939"/>
   <Location date="2019-04-03 19:50:57 +0900" latitude="35.0189" longitude="135.772" altitude="48.2096" horizontalAccuracy="1.78997" verticalAccuracy="1.26603" course="179.882" speed="1.4667"/>
   <Location date="2019-04-03 19:50:58 +0900" latitude="35.0189" longitude="135.772" altitude="48.179" horizontalAccuracy="1.7875" verticalAccuracy="1.26429" course="178.968" speed="1.47256"/>
   <Location date="2019-04-03 19:50:59 +0900" latitude="35.0188" longitude="135.772" altitude="48.1493" horizontalAccuracy="1.78522" verticalAccuracy="1.26267" course="182.289" speed="1.47677"/>
   <Location date="2019-04-03 19:51:00 +0900" latitude="35.0188" longitude="135.772" altitude="48.1208" horizontalAccuracy="1.78322" verticalAccuracy="1.26126" course="182.201" speed="1.47925"/>
   <Location date="2019-04-03 19:51:01 +0900" latitude="35.0188" longitude="135.772" altitude="48.0935" horizontalAccuracy="1.78158" verticalAccuracy="1.26009" course="185.844" speed="1.4801"/>
   <Location date="2019-04-03 19:51:02 +0900" latitude="35.0188" longitude="135.772" altitude="48.0676" horizontalAccuracy="1.78036" verticalAccuracy="1.25924" course="178.453" speed="1.47948"/>
   <Location date="2019-04-03 19:51:03 +0900" latitude="35.0188" longitude="135.772" altitude="48.0431" horizontalAccuracy="1.77964" verticalAccuracy="1.25873" course="177.087" speed="1.47761"/>
   <Location date="2019-04-03 19:51:04 +0900" latitude="35.0188" longitude="135.772" altitude="48.0202" horizontalAccuracy="1.77945" verticalAccuracy="1.25859" course="170.253" speed="1.47465"/>
   <Location date="2019-04-03 19:51:05 +0900" latitude="35.0188" longitude="135.772" altitude="47.9989" horizontalAccuracy="1.7798" verticalAccuracy="1.25884" course="172.378" speed="1.47077"/>
   <Location date="2019-04-03 19:51:06 +0900" latitude="35.0188" longitude="135.772" altitude="47.9791" horizontalAccuracy="1.78065" verticalAccuracy="1.25944" course="174.662" speed="1.46624"/>
   <Location date="2019-04-03 19:51:07 +0900" latitude="35.0187" longitude="135.772" altitude="47.9611" horizontalAccuracy="1.78194" verticalAccuracy="1.26035" course="178.97" speed="1.46131"/>
   <Location date="2019-04-03 19:51:08 +0900" latitude="35.0187" longitude="135.772" altitude="47.9446" horizontalAccuracy="1.78357" verticalAccuracy="1.26151" course="180.62" speed="1.45625"/>
   <Location date="2019-04-03 19:51:09 +0900" latitude="35.0187" longitude="135.772" altitude="47.9297" horizontalAccuracy="1.78544" verticalAccuracy="1.26283" course="176.492" speed="1.45129"/>
   <Location date="2019-04-03 19:51:10 +0900" latitude="35.0187" longitude="135.772" altitude="47.9163" horizontalAccuracy="1.78746" verticalAccuracy="1.26425" course="181.145" speed="1.44658"/>
   <Location date="2019-04-03 19:51:11 +0900" latitude="35.0187" longitude="135.772" altitude="47.9044" horizontalAccuracy="1.78952" verticalAccuracy="1.26571" course="187.577" speed="1.44219"/>
   <Location date="2019-04-03 19:51:12 +0900" latitude="35.0187" longitude="135.772" altitude="47.8939" horizontalAccuracy="1.79155" verticalAccuracy="1.26714" course="187.649" speed="1.43817"/>
   <Location date="2019-04-03 19:51:13 +0900" latitude="35.0187" longitude="135.772" altitude="47.8847" horizontalAccuracy="1.79344" verticalAccuracy="1.26848" course="188.712" speed="1.43458"/>
   <Location date="2019-04-03 19:51:14 +0900" latitude="35.0186" longitude="135.772" altitude="47.8768" horizontalAccuracy="1.79512" verticalAccuracy="1.26967" course="189.395" speed="1.43148"/>
   <Location date="2019-04-03 19:51:15 +0900" latitude="35.0186" longitude="135.772" altitude="47.87" horizontalAccuracy="1.79652" verticalAccuracy="1.27066" course="189.867" speed="1.42892"/>
   <Location date="2019-04-03 19:51:16 +0900" latitude="35.0186" longitude="135.772" altitude="47.8643" horizontalAccuracy="1.79757" verticalAccuracy="1.2714" course="194.039" speed="1.42695"/>
   <Location date="2019-04-03 19:51:17 +0900" latitude="35.0186" longitude="135.772" altitude="47.8596" horizontalAccuracy="1.79821" verticalAccuracy="1.27185" course="197.007" speed="1.4257"/>
   <Location date="2019-04-03 19:51:18 +0900" latitude="35.0186" longitude="135.772" altitude="47.8558" horizontalAccuracy="1.79843" verticalAccuracy="1.27201" course="195.552" speed="1.42531"/>
   <Location date="2019-04-03 19:51:19 +0900" latitude="35.0186" longitude="135.772" altitude="47.8529" horizontalAccuracy="1.79826" verticalAccuracy="1.27189" course="196.235" speed="1.42587"/>
   <Location date="2019-04-03 19:51:20 +0900" latitude="35.0186" longitude="135.772" altitude="47.8508" horizontalAccuracy="1.79779" verticalAccuracy="1.27155" course="193.943" speed="1.42744"/>
   <Location date="2019-04-03 19:51:21 +0900" latitude="35.0186" longitude="135.772" altitude="47.8494" horizontalAccuracy="1.79711" verticalAccuracy="1.27108" course="190.886" speed="1.43005"/>
   <Location date="2019-04-03 19:51:22 +0900" latitude="35.0185" longitude="135.772" altitude="47.8488" horizontalAccuracy="1.79636" verticalAccuracy="1.27054" course="190.755" speed="1.43372"/>
   <Location date="2019-04-03 19:51:23 +0900" latitude="35.0185" longitude="135.772" altitude="47.8489" horizontalAccuracy="1.79564" verticalAccuracy="1.27003" course="189.347" speed="1.43842"/>
   <Location date="2019-04-03 19:51:24 +0900" latitude="35.0185" longitude="135.772" altitude="47.8496" horizontalAccuracy="1.79504" verticalAccuracy="1.26961" course="190.035" speed="1.44403"/>
   <Location date="2019-04-03 19:51:25 +0900" latitude="35.0185" longitude="135.772" altitude="47.851" horizontalAccuracy="1.79461" verticalAccuracy="1.26931" course="188.098" speed="1.45037"/>
   <Location date="2019-04-03 19:51:26 +0900" latitude="35.0185" longitude="135.772" altitude="47.8531" horizontalAccuracy="1.79435" verticalAccuracy="1.26912" course="187.123" speed="1.45728"/>
   <Location date="2019-04-03 19:51:27 +0900" latitude="35.0185" longitude="135.772" altitude="47.8559" horizontalAccuracy="1.79419" verticalAccuracy="1.26901" course="186.199" speed="1.46452"/>
   <Location date="2019-04-03 19:51:28 +0900" latitude="35.0185" longitude="135.772" altitude="47.8594" horizontalAccuracy="1.79406" verticalAccuracy="1.26892" course="188.878" speed="1.47185"/>
   <Location date="2019-04-03 19:51:29 +0900" latitude="35.0185" longitude="135.772" altitude="47.8635" horizontalAccuracy="1.79384" verticalAccuracy="1.26876" course="188.799" speed="1.47907"/>